name: CI/CD Pipeline - Node Hello World

on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest

steps:
# -------------------------
# 1. Checkout Repository
# -------------------------
- name: Checkout Code
uses: actions/checkout@v3

# -------------------------
# 2. Set up Node.js
# -------------------------
- name: Use Node.js
uses: actions/setup-node@v3
with:
node-version: '18'

# -------------------------
# 3. Install Dependencies
# -------------------------
- name: Install Dependencies
run: npm install

# -------------------------
# 4. Build Docker Image
# -------------------------
- name: Build Docker Image
run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-hello:latest .

# -------------------------
# 5. Login to Docker Hub
# -------------------------
- name: Login to DockerHub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKER_HUB_USERNAME }}
password: ${{ secrets.DOCKER_HUB_PASSWORD }}

# -------------------------
# 6. Push image to Docker Hub
# -------------------------
- name: Push Docker Image
run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-hello:latest

# -------------------------
# 7. Deploy to AWS EC2 using SSH
# -------------------------
- name: Deploy to AWS EC2
uses: appleboy/ssh-action@v0.1.10
with:
host: ${{ secrets.EC2_PUBLIC_IP }}
username: ubuntu
key: ${{ secrets.EC2_SSH_KEY }}
script: |
sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/node-hello:latest
sudo docker stop nodehello || true
sudo docker rm nodehello || true
sudo docker run -d -p 80:3000 --name nodehello ${{ secrets.DOCKER_HUB_USERNAME }}/node-hello:latest
